### ISSUE TITLE
MCTowns Load Error

### ISSUE THREAD

**Issue by jgrimes900** [jmhertlein/MCTowns#69]
here is the error log!

[18:34:29 ERROR]: Error occurred while enabling MCTowns v2.4.0-6650f896d5e388047388965084ae7cf0282086da (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldguard/protection/managers/storage/StorageException
        at net.jmhertlein.mctowns.MCTownsPlugin.setupTownManager(MCTownsPlugin.java:163) ~[?:?]
        at net.jmhertlein.mctowns.MCTownsPlugin.onEnable(MCTownsPlugin.java:121) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit_server.jar:git-Bukkit-ee6d0fa]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [craftbukkit_server.jar:git-Bukkit-ee6d0fa]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit_server.jar:git-Bukkit-ee6d0fa]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:341) [craftbukkit_server.jar:git-Bukkit-ee6d0fa]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:313) [craftbukkit_server.jar:git-Bukkit-ee6d0fa]
        at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:394) [craftbukkit_server.jar:git-Bukkit-ee6d0fa]
        at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:362) [craftbukkit_server.jar:git-Bukkit-ee6d0fa]
        at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:317) [craftbukkit_server.jar:git-Bukkit-ee6d0fa]
        at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:190) [craftbukkit_server.jar:git-Bukkit-ee6d0fa]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:484) [craftbukkit_server.jar:git-Bukkit-ee6d0fa]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.protection.managers.storage.StorageException
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[?:1.7.0_75]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_75]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_75]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_75]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit_server.jar:git-Bukkit-ee6d0fa]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit_server.jar:git-Bukkit-ee6d0fa]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_75]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_75]

**Comment by jmhertlein** [comment]
Please install WorldGuard and WorldEdit.

**Comment by jmhertlein** [comment]
Specifically, the latest version (6.0+) of WorldGuard.

**Comment by jgrimes900** [comment]
I will try that!
