### ISSUE TITLE
Town Manager issue

### ISSUE THREAD

**Issue by hockeymikey** [jmhertlein/MCTowns#85]
Getting the town manager just like it was outlined in the wiki.  It worked before but now I'm getting the following error.  Using and compiling with 2.4.0
`java.lang.NoSuchMethodError: net.jmhertlein.mctowns.MCTowns.getTownManager()Lnet/jmhertlein/mctowns/TownManager;
    at mn.hockeymikey.grottocore.GrottoCore.onEnable(GrottoCore.java:228) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-db6de12-07c3001]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-07c3001]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-07c3001]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-07c3001]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-07c3001]
    at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-db6de12-07c3001]
    at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-db6de12-07c3001]
    at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-db6de12-07c3001]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-db6de12-07c3001]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-07c3001]`

**Comment by jmhertlein** [comment]
Weird. Link your pom.xml?

**Comment by hockeymikey** [comment]
http://pastebin.com/Hz6vChLq

Same issue using 2.5.0 from your maven too.  I copied the most recent 2.4.0 jar from spigot/bukkit into my local repository.

**Comment by hockeymikey** [comment]
So compiled 2.5.0 and that works fine with the plugin.

**Comment by hockeymikey** [comment]
This would work fine but MCTowns becomes even more confusing for players with this.  The help messages offer no help at all.  Like for addtown complained about missing an string array parameter.  New players would be very confused by this and probably only think it needs one string.  I think reflective needs that added support to define a help message for a command (unless it's already there).
